In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
from scipy.stats import norm, skew #加载一些统计的库

In [3]:
data = pd.read_table('train.txt',sep=' ',index_col=False) 

In [4]:
data2 = pd.read_csv('1234.csv',index_col=False) 

In [5]:
data2a = pd.read_csv('two_test.csv',index_col=False) 

In [6]:
dataa = pd.read_csv('two_train.csv',index_col=False) 

In [7]:
data2c = pd.read_csv('test_clickpv.csv',index_col=False) 

In [8]:
datac = pd.read_csv('clickpv.csv',index_col=False) 

In [9]:
print(dataa.shape)
print(data2a.shape)

(478138, 32)
(18371, 31)


In [10]:
data.insert(1, 'click', dataa[[ 'click']])
data.insert(1, 'zhuanhualv', dataa[[ 'zhuanhualv']])
data.insert(1, 'relaofzhuanhuaanddianji', dataa[[ 'relaofzhuanhuaanddianji']])
data.insert(1, 'pinpai_buy_lv', dataa[[ 'pinpai_buy_lv']])
data.insert(1, 'pinpai_click', dataa[[ 'pinpai_click']])
data.insert(1, 'clickpv', datac[[ 'clickpv']])

In [11]:
data.pop('item_category_list')
data.insert(1, 'item_category_list', data2[['item_category_list']])
data.pop('item_property_list')
data.insert(2, 'item_property_list', data2[['item_property_list']])
pass

In [12]:
data[['context_timestamp']] = data[['context_timestamp']] - 1537200000

In [13]:
data

instance_id  item_category_list  item_property_list  clickpv  \
0        108641074714126964                   2                   0     0.01   
1       5754713551599725161                   2                   1     0.01   
2        842679481291040981                   2                   3     0.01   
3        937088850059189027                   2                   0     0.01   
4       7975697065017708072                   2                   2     0.01   
5       7764762765372067286                   2                   2     0.01   
6       6956333474094867789                   2                   3     0.01   
7       8387099821892927911                   2                   3     0.01   
8       4021878205550012615                   2                   0     0.01   
9       6499571365974135517                   2                   1     0.01   
10      2880717957514996136                   2                   3     0.01   
11       939825752961345523                   1                   0     0.01   
12      8802991093903959363                   2                   0     0.01   
13      3368094606870610045                   2                   0     0.01   
14      7972325483281584825                   2                   3     0.01   
15      8277925953313664420                   2                   0     0.01   
16      6534421086843299211                   2                   1     0.01   
17      3463502729031605090                   1                   1     0.01   
18      8460619240681789215                   2                   3     0.01   
19      5394134991759971072                   2                   1     0.01   
20      8100317749857990669                   2                   0     0.01   
21      4876117478498068156                   2                   1     0.01   
22      7175346699535417471                   2                   0     0.01   
23      1717647750027035965                   1                   1     0.01   
24      3354341427042173935                   1                   1     0.01   
25      5745320053832775381                   1                   1     0.01   
26      5434151906459196590                   2                   1     0.01   
27      6177436254635040085                   2                   0     0.01   
28      5570891913513111784                   2                   0     0.01   
29      5978989494083802018                   2                   1     0.01   
...                     ...                 ...                 ...      ...   
478108  4651714268781123949                   2                   1     0.04   
478109  5390266520663927871                   2                   1     0.05   
478110  2981469789352227651                   2                   0     0.01   
478111  8970485803523828918                   2                   0     0.06   
478112  3025412137450773218                   2                   0     0.04   
478113   821625033894076557                   2                   0     0.04   
478114  4962352896175877536                   1                   0     0.13   
478115   613658182524644178                   2                   2     0.08   
478116  8964303781074834102                   2                   0     0.06   
478117  8319941530071813935                   1                   0     0.03   
478118  6484564790810402673                   1                   0     0.06   
478119  4127606297457513734                   2                   1     0.04   
478120   740664466225961867                   2                   1     0.03   
478121  7752959112678967031                   2                   2     0.06   
478122  2960327362008121421                   1                   1     0.01   
478123  3335455775042655938                   1                   0     0.03   
478124  3170566302563685363                   2                   1     0.03   
478125  6247775901908102838                   2                   2     0.02   
478126  11047135

In [14]:
X = data[[ 
          'shop_review_positive_rate','shop_score_service',
         'shop_score_delivery','shop_score_description','shop_star_level'
          ,'shop_review_num_level','item_price_level','item_sales_level',
         'item_collected_level','item_pv_level',
          'user_gender_id','user_age_level',
          'user_occupation_id','user_star_level',
          'context_page_id','context_timestamp',
            'relaofzhuanhuaanddianji', 'click', 'pinpai_click','clickpv']]
Y = data[['is_trade']]
X = np.array(X)
Y = np.array(Y).ravel()

In [15]:
# 制作训练集与测试集并且进行预处理
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=666)

In [16]:
# X_shop_train = X_train[:, :6]
# X_item_train = X_train[:, 6:10]
# X_user_train = X_train[:, 10:13]
# X_content_train = X_train[:, 13:15]
# X_shop_test = X_test[:, :6]
# X_item_test = X_test[:, 6:10]
# X_user_test = X_test[:, 10:13]
# X_content_test = X_test[:, 13:15]

In [17]:
train = X_train
test = X_test

## 加载测试集

In [18]:
data2 = pd.read_table('test.txt',sep=' ',index_col=False) 

In [19]:
data3 = pd.read_csv('456.csv',index_col=False) 

In [20]:
data2.insert(1, 'click', data2a[[ 'click']])
data2.insert(1, 'zhuanhualv', data2a[['zhuanhualv']])
data2.insert(1, 'relaofzhuanhuaanddianji', data2a[[ 'relaofzhuanhuaanddianji']])
data2.insert(1, 'pinpai_buy_lv', data2a[[ 'pinpai_buy_lv']])
data2.insert(1, 'pinpai_click', data2a[[ 'pinpai_click']])
data2.insert(1, 'clickpv', data2c[[ 'clickpv']])

In [21]:
data2.pop('item_category_list')
data2.insert(1, 'item_category_list', data3[['item_category_list']])
data2.pop('item_property_list')
data2.insert(2, 'item_property_list', data3[['item_property_list']])
pass

In [22]:
data2[['context_timestamp']] = data2[['context_timestamp']] - 1537200000

In [23]:
data2a.columns

Index(['instance_id', 'item_id', 'item_category_list', 'item_property_list',
       'item_brand_id', 'item_city_id', 'item_price_level', 'item_sales_level',
       'item_collected_level', 'item_pv_level', 'user_id', 'user_gender_id',
       'user_age_level', 'user_occupation_id', 'user_star_level', 'context_id',
       'context_timestamp', 'context_page_id', 'predict_category_property',
       'shop_id', 'shop_review_num_level', 'shop_review_positive_rate',
       'shop_star_level', 'shop_score_service', 'shop_score_delivery',
       'shop_score_description', 'click', 'zhuanhualv',
       'relaofzhuanhuaanddianji', 'pinpai_click', 'pinpai_buy_lv'],
      dtype='object')

In [24]:
# X_pre = data2[['item_category_list','item_property_list',
#           'zhuanhualv','relaofzhuanhuaanddianji', 
#           'pinpai_buy_lv', 'pinpai_click',
#           'shop_review_positive_rate','shop_score_service',
#          'shop_score_delivery','shop_score_description','shop_star_level'
#           ,'shop_review_num_level','item_price_level','item_sales_level',
#          'item_collected_level','item_pv_level',
#           'user_gender_id','user_age_level',
#           'user_occupation_id','user_star_level',
#           'context_page_id','context_timestamp']]
X_pre = data2[[ 
          'shop_review_positive_rate','shop_score_service',
         'shop_score_delivery','shop_score_description','shop_star_level'
          ,'shop_review_num_level','item_price_level','item_sales_level',
         'item_collected_level','item_pv_level',
          'user_gender_id','user_age_level',
          'user_occupation_id','user_star_level',
          'context_page_id','context_timestamp',
            'relaofzhuanhuaanddianji', 'click', 'pinpai_click','clickpv']]
X_pre = np.array(X_pre,dtype='float')

In [25]:
X_pre[10,:]

array([  1.00000000e+00,   9.79252459e-01,   9.80537705e-01,
         9.85626230e-01,   5.01200000e+03,   1.50000000e+01,
         8.00000000e+00,   1.00000000e+01,   1.30000000e+01,
         1.50000000e+01,   1.00000000e+00,   1.00200000e+03,
         2.00500000e+03,   3.00700000e+03,   4.00100000e+03,
         6.66277000e+05,   0.00000000e+00,   0.00000000e+00,
         1.16000000e+02,   1.00000000e-02])

## 分箱

In [26]:
#item_price_level
# bins = np.linspace(-0.5, 2.5, 4)
sha = train.shape[1]
for i in range(4,sha-5):
# i = 4
# if True:
    print((X_train[:,i][X_train[:,i]>=0].max()+1.5)-(X_train[:,i][X_train[:,i]>=0].min()-0.5))
    bins = np.arange(X_train[:,i][(X_train[:,i]>=0)].min()-0.5, X_train[:,i][X_train[:,i]>=0].max()+1.5, 1)
    bins = np.hstack(([-1.5],bins))
    which_bin = np.digitize(train[:,i].reshape(-1, 1), bins=bins)
    encoder = OneHotEncoder(sparse=False)
    encoder.fit(which_bin)
    X_train_binned = encoder.transform(which_bin)



    which_bin = np.digitize(test[:,i].reshape(-1, 1), bins=bins)
#     encoder = OneHotEncoder(sparse=False)
#     encoder.fit(which_bin)
    X_test_binned = encoder.transform(which_bin)
    
    which_bin = np.digitize(X_pre[:,i].reshape(-1, 1), bins=bins)
#     encoder = OneHotEncoder(sparse=False)
#     encoder.fit(which_bin)
    X_pre_binned = encoder.transform(which_bin)
    print(bins)
    if (np.hstack((train,X_train_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
        if (np.hstack((X_pre,X_pre_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
            train = np.hstack((train,X_train_binned))
            test = np.hstack((test,X_test_binned))
            X_pre = np.hstack((X_pre,X_pre_binned))
            print("0k")
    else:
        print("No")

23.0
[ -1.50000000e+00   4.99850000e+03   4.99950000e+03   5.00050000e+03
   5.00150000e+03   5.00250000e+03   5.00350000e+03   5.00450000e+03
   5.00550000e+03   5.00650000e+03   5.00750000e+03   5.00850000e+03
   5.00950000e+03   5.01050000e+03   5.01150000e+03   5.01250000e+03
   5.01350000e+03   5.01450000e+03   5.01550000e+03   5.01650000e+03
   5.01750000e+03   5.01850000e+03   5.01950000e+03   5.02050000e+03]
0k
27.0
[ -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5
  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5  18.5  19.5  20.5  21.5
  22.5  23.5  24.5  25.5]
0k
19.0
[ -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5
  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5]
0k
18.0
[ -1.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5  10.5
  11.5  12.5  13.5  14.5  15.5  16.5  17.5]
0k
19.0
[ -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5
  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5]
0k
23.0
[ -1.

In [27]:
bins = np.linspace(0, 86400,49)
print(bins)
bins = np.hstack(([-1.5],bins))
which_bin = np.digitize(train[:,15].reshape(-1, 1), bins=bins)
encoder = OneHotEncoder(sparse=False)
encoder.fit(which_bin)
X_train_binned = encoder.transform(which_bin)



which_bin = np.digitize(test[:,15].reshape(-1, 1), bins=bins)
# encoder = OneHotEncoder(sparse=False)
# encoder.fit(which_bin)
X_test_binned = encoder.transform(which_bin)

which_bin = np.digitize(X_pre[:,15].reshape(-1, 1), bins=bins)
# encoder = OneHotEncoder(sparse=False)
# encoder.fit(which_bin)
X_pre_binned = encoder.transform(which_bin)
print(bins)
if (np.hstack((train,X_train_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
    if (np.hstack((X_pre,X_pre_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
        train = np.hstack((train,X_train_binned))
        test = np.hstack((test,X_test_binned))
        X_pre = np.hstack((X_pre,X_pre_binned))
        print("0k")
else:
    print("No")

[     0.   1800.   3600.   5400.   7200.   9000.  10800.  12600.  14400.
  16200.  18000.  19800.  21600.  23400.  25200.  27000.  28800.  30600.
  32400.  34200.  36000.  37800.  39600.  41400.  43200.  45000.  46800.
  48600.  50400.  52200.  54000.  55800.  57600.  59400.  61200.  63000.
  64800.  66600.  68400.  70200.  72000.  73800.  75600.  77400.  79200.
  81000.  82800.  84600.  86400.]
[ -1.50000000e+00   0.00000000e+00   1.80000000e+03   3.60000000e+03
   5.40000000e+03   7.20000000e+03   9.00000000e+03   1.08000000e+04
   1.26000000e+04   1.44000000e+04   1.62000000e+04   1.80000000e+04
   1.98000000e+04   2.16000000e+04   2.34000000e+04   2.52000000e+04
   2.70000000e+04   2.88000000e+04   3.06000000e+04   3.24000000e+04
   3.42000000e+04   3.60000000e+04   3.78000000e+04   3.96000000e+04
   4.14000000e+04   4.32000000e+04   4.50000000e+04   4.68000000e+04
   4.86000000e+04   5.04000000e+04   5.22000000e+04   5.40000000e+04
   5.58000000e+04   5.76000000e+04   5.94000000e+

In [28]:
test.shape

(119535, 238)

In [29]:
# PF = PolynomialFeatures(degree=2)
# PF.fit(train)
# X_train = PF.transform(train)
# X_test = PF.transform(test)

In [30]:
SS = StandardScaler()
SS.fit(train)
train = SS.transform(train)
test = SS.transform(test)
X_pre = SS.transform(X_pre)

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.externals import joblib
from sklearn.metrics import log_loss
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC

import xgboost as xgb
import lightgbm as lgb

In [32]:
xgb?

In [62]:
model_xgb = xgb.XGBClassifier( n_estimators=400,random_state =666, nthread = -1,n_jobs=-1)

In [63]:
model_xgb.fit(train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=400,
       n_jobs=-1, nthread=-1, objective='binary:logistic',
       random_state=666, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1)

In [64]:
xgb_train_pred = model_xgb.predict_proba(train)
log_loss(Y_train, xgb_train_pred[:,1])

0.086127390526280198

In [65]:
xgb_test_pred = model_xgb.predict_proba(test)
log_loss(Y_test, xgb_test_pred[:,1])

0.087471731894863

In [66]:
model_xgb.predict_proba(X_pre)[:,1]

array([ 0.00464319,  0.00950932,  0.01936598, ...,  0.00799046,
        0.0410134 ,  0.01485141], dtype=float32)

In [38]:
874

874

In [39]:
xgb1 = model_xgb

In [58]:
model_lgb = lgb.LGBMClassifier(n_estimators=100,n_jobs=-1,min_child_samples=500,
                              feature_fraction_seed=666, bagging_seed=666)

In [59]:
model_lgb.fit(train, Y_train)

LGBMClassifier(bagging_seed=666, boosting_type='gbdt', class_weight=None,
        colsample_bytree=1.0, feature_fraction_seed=666, learning_rate=0.1,
        max_depth=-1, min_child_samples=500, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=None, reg_alpha=0.0, reg_lambda=0.0,
        silent=True, subsample=1.0, subsample_for_bin=200000,
        subsample_freq=1)

In [60]:
lgb_train_pred = model_lgb.predict_proba(train)
log_loss(Y_train, lgb_train_pred[:,1])

0.085268233412610805

In [61]:
lgb_test_pred = model_lgb.predict_proba(test)
log_loss(Y_test, lgb_test_pred[:,1])

0.087338022442155896

In [57]:
model_lgb.predict_proba(X_pre)[:,1]

array([ 0.00480042,  0.02034508,  0.02861821, ...,  0.02615311,
        0.07096084,  0.02628773])

In [45]:
876

876

In [67]:
lgb_test_pred = model_lgb.predict_proba(test)
xgb_test_pred = model_xgb.predict_proba(test)
log_loss(Y_test, (xgb_test_pred[:,1]+xgb_test_pred[:,1])/2)

0.087471731894863

In [68]:
log_loss(Y_test, (xgb_test_pred[:,1]+xgb_test_pred[:,1])/2)

0.087471731894863

In [75]:
log_reg = LogisticRegression(C = 0.01,penalty='l1')
log_reg.fit(train, Y_train)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [76]:
log_loss(Y_train, log_reg.predict_proba(train)[:,1])

0.089838289612323471

In [77]:
log_loss(Y_test, log_reg.predict_proba(test)[:,1])

0.08838262200701745

In [78]:
log_reg.predict_proba(test)[:,1]

array([ 0.00854885,  0.02639892,  0.01250593, ...,  0.03293847,
        0.01413626,  0.02508614])

In [72]:
lgb_test_pred = model_lgb.predict_proba(train)
xgb_test_pred = model_xgb.predict_proba(train)
X_add = np.hstack((lgb_test_pred, xgb_test_pred))

In [73]:
log_all = LogisticRegression()
log_all.fit(X_add, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [74]:
log_loss(Y_train, log_all.predict_proba(X_add)[:,1])

0.08711101159725583

In [75]:
lgb_test_pred = model_lgb.predict_proba(test)
xgb_test_pred = model_xgb.predict_proba(test)
X_add = np.hstack((lgb_test_pred, xgb_test_pred))

In [76]:
log_loss(Y_test, log_all.predict_proba(X_add)[:,1])

0.088584669613493622

In [82]:
lgb_test_pred = model_lgb.predict_proba(test)
xgb_test_pred = model_xgb.predict_proba(test)
X_add = np.hstack((lgb_test_pred, xgb_test_pred))

In [83]:
log_loss(Y_test, log_all.predict_proba(X_add)[:,1])

0.089675369764396301

In [83]:
# BC = BaggingClassifier(base_estimator=LogisticRegression(C = 0.01), random_state=666, n_estimators=30)
# BC.fit(train, Y_train)

In [28]:
# log_loss(Y_train, BC.predict_proba(train))

In [29]:
# log_loss(Y_test, BC.predict_proba(test))

In [30]:
# log_reg.predict_proba(train)[:,1]

In [31]:
# ETR = joblib.load('allETR.pkl')
# ETR = ExtraTreesClassifier(n_estimators=300, n_jobs=-1, random_state=666, max_depth=500)#0.41
# ETR.fit(train, Y_train)

In [32]:
# log_loss(Y_train, ETR.predict_proba(train)[:,1])

In [33]:
# log_loss(Y_test, ETR.predict_proba(test)[:,1])

In [34]:
# joblib.dump(ETR, 'allETR.pkl') 

In [35]:
MNB = MultinomialNB(alpha=1)
MNB.fit(train+1, Y_train)

MultinomialNB(alpha=1, class_prior=None, fit_prior=True)

In [36]:
log_loss(Y_test, MNB.predict_proba(test+1)[:,1])

16.115579524976997

In [37]:
BNB = BernoulliNB(alpha=1)
BNB.fit(train+1, Y_train)

BernoulliNB(alpha=1, binarize=0.0, class_prior=None, fit_prior=True)

In [38]:
log_loss(Y_test, BNB.predict_proba(test)[:,1])

33.901286592858881

In [63]:
log_loss(Y_test, np.ones([Y_test.shape[0],1])*0.01*4)

0.099552248514805805

In [51]:
np.ones([Y_test.shape[0],1])*0.000000001*4

array([[  4.00000000e-09],
       [  4.00000000e-09],
       [  4.00000000e-09],
       ..., 
       [  4.00000000e-09],
       [  4.00000000e-09],
       [  4.00000000e-09]])

In [48]:
np.zeros([Y_test.shape[0],1])

array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [39]:
# last = LogisticRegression(C = 0.0008,penalty='l2')

# # log_reg.fit(train, Y_train)
# # ETR.fit(train, Y_train)
# # MNB.fit(train+1, Y_train)
# # BNB.fit(train+1, Y_train)
# c_data = log_reg.predict_proba(train)[:, 1].reshape(-1, 1)
# c_data = np.hstack((c_data,ETR.predict_proba(train)[:, 1].reshape(-1, 1)))
# c_data = np.hstack((c_data,MNB.predict_proba(train+1)[:, 1].reshape(-1, 1)))
# # c_data = np.hstack((c_data,BNB.predict_proba(train+1)[:, 1].reshape(-1, 1)))
# last.fit(c_data,Y_train)


In [40]:
# Y_pre1 = log_reg.predict_proba(train)[:, 1].reshape(-1, 1)
# Y_pre2 = ETR.predict_proba(train)[:, 1].reshape(-1, 1)
# Y_pre3 = MNB.predict_proba(train+1)[:, 1].reshape(-1, 1)
# # Y_pre4 = BNB.predict_proba(train+1)[:, 1].reshape(-1, 1)
# Y_add = np.hstack((Y_pre1, Y_pre2))
# Y_add = np.hstack((Y_add, Y_pre3))
# # Y_add = np.hstack((Y_add, Y_pre4))
# Y_pre = last.predict_proba(Y_add)

In [41]:
# log_loss(Y_train, Y_pre)

In [42]:
# log_loss(Y_test, last.predict_proba(np.hstack((log_reg.predict_proba(test)[:, 1].reshape(-1, 1),ETR.predict_proba(test)[:, 1].reshape(-1, 1)))))

In [43]:
# Y_pre1 = log_reg.predict_proba(test)[:, 1].reshape(-1, 1)
# Y_pre2 = ETR.predict_proba(test)[:, 1].reshape(-1, 1)
# Y_pre3 = MNB.predict_proba(test+1)[:, 1].reshape(-1, 1)
# # Y_pre4 = BNB.predict_proba(test+1)[:, 1].reshape(-1, 1)
# Y_add = np.hstack((Y_pre1, Y_pre2))
# Y_add = np.hstack((Y_add, Y_pre3))
# # Y_add = np.hstack((Y_add, Y_pre4))
# Y_pre = last.predict_proba(Y_add)

# # Y_pre = Y_pre1 + Y_pre2 + Y_pre3 + Y_pre4
# # Y_pre = Y_pre/4

In [44]:
# log_loss(Y_test, Y_pre)

In [45]:
# Y_pre = ETR.predict_proba(X_pre)
# Y_pre

In [77]:
Y_pre = log_reg.predict_proba(X_pre)[:,1]
Y_pre = Y_pre.reshape(-1,1)
Y_prelist = Y_pre.tolist()

In [78]:
Y_prelist

[[0.0046431878581643105],
 [0.009509317576885223],
 [0.019365979358553886],
 [0.02037646248936653],
 [0.012052217498421669],
 [0.008960563689470291],
 [0.036466311663389206],
 [0.008568317629396915],
 [0.005505737382918596],
 [0.006846429314464331],
 [0.005981637164950371],
 [0.005664622411131859],
 [0.004932793322950602],
 [0.0210989098995924],
 [0.0071770139038562775],
 [0.006416521966457367],
 [0.005068987142294645],
 [0.011705668643116951],
 [0.0067966170608997345],
 [0.008868664503097534],
 [0.02161259949207306],
 [0.002675173105672002],
 [0.001457499573007226],
 [0.0018567921360954642],
 [0.0034473470877856016],
 [0.00159956025891006],
 [0.001964984927326441],
 [0.00156093155965209],
 [0.002456458518281579],
 [0.0033379392698407173],
 [0.002155508380383253],
 [0.003286865772679448],
 [0.001457499573007226],
 [0.0038271641824394464],
 [0.002819944405928254],
 [0.0011488309828564525],
 [0.0034898673184216022],
 [0.002108408370986581],
 [0.0031373538076877594],
 [0.00243449653498828

In [65]:
Y_pre = (model_lgb.predict_proba(X_pre)[:,1]+model_xgb.predict_proba(X_pre)[:,1])/2
Y_pre = Y_pre.reshape(-1,1)
Y_prelist = Y_pre.tolist()

In [92]:
# sub = pd.DataFrame()
# sub['instance_id'] = np.array(data2[['instance_id']],dtype='float').ravel()
# sub['predicted_score'] = Y_pre[:,1].ravel()
# sub.to_csv('submission.csv',index=False)

In [ ]:
instance_id = np.array(data2[['instance_id']],dtype='float').ravel()
instance_idlist = instance_id.tolist()
with open('111.txt', 'w') as f:
    f.write("instance_id predicted_score\r") 
    for i in range(Y_pre.shape[0]):
        f.write(str(data2[['instance_id']].iloc[i,0]) + " " + str(Y_pre[i][0]) + '\r') 
#         f.write(str(data2[['instance_id']].iloc[i,0]) + " " + str('%.15f'%Y_pre[i,0]) + '\r') 

In [436]:
Y_pre.shape[0]

18371

In [570]:
np.set_printoptions(suppress=True)

In [584]:
'%.15f'%Y_pre[0,0]

'0.000002709476912'

In [50]:
# data2[['instance_id']]

In [51]:
# sub = pd.DataFrame()
# sub['instance_id'] = data2.pop('instance_id')
# sub['predicted_score'] = Y_pre[:,1].ravel().reshape(-1, 1)
# sub.to_csv('000.txt',index=False, sep=' ')