In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats
from scipy.stats import norm, skew #加载一些统计的库

In [13]:
data = pd.read_table('train.txt',sep=' ',index_col=False) 

In [14]:
data2 = pd.read_csv('1234.csv',index_col=False) 

In [15]:
data2a = pd.read_csv('two_test.csv',index_col=False) 

In [16]:
dataa = pd.read_csv('two_train.csv',index_col=False) 

In [17]:
data2c = pd.read_csv('test_clickpv.csv',index_col=False) 

In [18]:
datac = pd.read_csv('clickpv.csv',index_col=False) 

In [19]:
data2d = pd.read_csv('three_test.csv',index_col=False) 

In [20]:
datad = pd.read_csv('three_train.csv',index_col=False) 

In [21]:
# datad

In [22]:
data.insert(1, 'click', dataa[[ 'click']])
data.insert(1, 'zhuanhualv', dataa[[ 'zhuanhualv']])
data.insert(1, 'relaofzhuanhuaanddianji', dataa[[ 'relaofzhuanhuaanddianji']])
data.insert(1, 'pinpai_buy_lv', dataa[[ 'pinpai_buy_lv']])
data.insert(1, 'pinpai_click', dataa[[ 'pinpai_click']])
data.insert(1, 'clickpv', datac[[ 'clickpv']])
data.insert(1, 'like_top_one_jiagelevel', datad[[ 'like_top_one_jiagelevel']])
data.insert(1, 'like_top_two_jiagelevel', datad[[ 'like_top_two_jiagelevel']])
data.insert(1, 'like_top_three_jiagelevel', datad[[ 'like_top_three_jiagelevel']])
data.insert(1, 'like_top_one_jiageclick', datad[[ 'like_top_one_jiageclick']])
data.insert(1, 'like_top_two_jiageclick', datad[[ 'like_top_two_jiageclick']])
data.insert(1, 'like_top_three_jiageclick', datad[[ 'like_top_three_jiageclick']])

In [23]:
# data.pop('item_category_list')
data.insert(1, 'item_category_list_num', data2[['item_category_list']])
# data.pop('item_property_list')
data.insert(2, 'item_property_list_num', data2[['item_property_list']])
pass

In [24]:
data[['context_timestamp']] = data[['context_timestamp']] - 1537200000

In [25]:
data

instance_id  item_category_list_num  item_property_list_num  \
0        108641074714126964                       2                       0   
1       5754713551599725161                       2                       1   
2        842679481291040981                       2                       3   
3        937088850059189027                       2                       0   
4       7975697065017708072                       2                       2   
5       7764762765372067286                       2                       2   
6       6956333474094867789                       2                       3   
7       8387099821892927911                       2                       3   
8       4021878205550012615                       2                       0   
9       6499571365974135517                       2                       1   
10      2880717957514996136                       2                       3   
11       939825752961345523                       1                       0   
12      8802991093903959363                       2                       0   
13      3368094606870610045                       2                       0   
14      7972325483281584825                       2                       3   
15      8277925953313664420                       2                       0   
16      6534421086843299211                       2                       1   
17      3463502729031605090                       1                       1   
18      8460619240681789215                       2                       3   
19      5394134991759971072                       2                       1   
20      8100317749857990669                       2                       0   
21      4876117478498068156                       2                       1   
22      7175346699535417471                       2                       0   
23      1717647750027035965                       1                       1   
24      3354341427042173935                       1                       1   
25      5745320053832775381                       1                       1   
26      5434151906459196590                       2                       1   
27      6177436254635040085                       2                       0   
28      5570891913513111784                       2                       0   
29      5978989494083802018                       2                       1   
...                     ...                     ...                     ...   
478108  4651714268781123949                       2                       1   
478109  5390266520663927871                       2                       1   
478110  2981469789352227651                       2                       0   
478111  8970485803523828918                       2                       0   
478112  3025412137450773218                       2                       0   
478113   821625033894076557                       2                       0   
478114  4962352896175877536                       1                       0   
478115   613658182524644178                       2                       2   
478116  8964303781074834102                       2                       0   
478117  8319941530071813935                       1                       0   
478118  6484564790810402673                       1                       0   
478119  4127606297457513734                       2                       1   
478120   740664466225961867                       2                       1   
478121  7752959112678967031                       2                       2   
478122  2960327362008121421                       1                       1   
478123  3335455775042655938                       1                       0   
478124  3170566302563685363                       2                       1   
478125  6247775901908102838                       2                       2   
478126  1104713591881111654                       2               

In [26]:
X = data[[ 
          'shop_review_positive_rate','shop_score_service',
         'shop_score_delivery','shop_score_description','shop_star_level'
          ,'shop_review_num_level','item_price_level','item_sales_level',
         'item_collected_level','item_pv_level',
          'user_gender_id','user_age_level',
          'user_occupation_id','user_star_level','item_category_list_num','item_property_list_num',
          'context_page_id','context_timestamp',
            'like_top_one_jiageclick','like_top_two_jiageclick','like_top_three_jiageclick'
            ,'clickpv']]
Y = data[['is_trade']]
X = np.array(X)
Y = np.array(Y).ravel()

In [27]:
# 制作训练集与测试集并且进行预处理
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=666)

In [28]:
# X_shop_train = X_train[:, :6]
# X_item_train = X_train[:, 6:10]
# X_user_train = X_train[:, 10:13]
# X_content_train = X_train[:, 13:15]
# X_shop_test = X_test[:, :6]
# X_item_test = X_test[:, 6:10]
# X_user_test = X_test[:, 10:13]
# X_content_test = X_test[:, 13:15]

In [29]:
train = X_train
test = X_test

## 加载测试集

In [30]:
data2 = pd.read_table('test.txt',sep=' ',index_col=False) 

In [31]:
data3 = pd.read_csv('456.csv',index_col=False) 

In [32]:
data2.insert(1, 'click', data2a[[ 'click']])
data2.insert(1, 'zhuanhualv', data2a[['zhuanhualv']])
data2.insert(1, 'relaofzhuanhuaanddianji', data2a[[ 'relaofzhuanhuaanddianji']])
data2.insert(1, 'pinpai_buy_lv', data2a[[ 'pinpai_buy_lv']])
data2.insert(1, 'pinpai_click', data2a[[ 'pinpai_click']])
data2.insert(1, 'clickpv', data2c[[ 'clickpv']])
data2.insert(1, 'like_top_one_jiagelevel', data2d[[ 'like_top_one_jiagelevel']])
data2.insert(1, 'like_top_two_jiagelevel', data2d[[ 'like_top_two_jiagelevel']])
data2.insert(1, 'like_top_three_jiagelevel', data2d[[ 'like_top_three_jiagelevel']])
data2.insert(1, 'like_top_one_jiageclick', data2d[[ 'like_top_one_jiageclick']])
data2.insert(1, 'like_top_two_jiageclick', data2d[[ 'like_top_two_jiageclick']])
data2.insert(1, 'like_top_three_jiageclick', data2d[[ 'like_top_three_jiageclick']])

In [33]:
# data2.pop('item_category_list')
data2.insert(1, 'item_category_list_num', data3[['item_category_list']])
# data2.pop('item_property_list')
data2.insert(2, 'item_property_list_num', data3[['item_property_list']])
pass

In [34]:
data2[['context_timestamp']] = data2[['context_timestamp']] - 1537200000

In [35]:
data2a.columns

Index(['instance_id', 'item_id', 'item_category_list', 'item_property_list',
       'item_brand_id', 'item_city_id', 'item_price_level', 'item_sales_level',
       'item_collected_level', 'item_pv_level', 'user_id', 'user_gender_id',
       'user_age_level', 'user_occupation_id', 'user_star_level', 'context_id',
       'context_timestamp', 'context_page_id', 'predict_category_property',
       'shop_id', 'shop_review_num_level', 'shop_review_positive_rate',
       'shop_star_level', 'shop_score_service', 'shop_score_delivery',
       'shop_score_description', 'click', 'zhuanhualv',
       'relaofzhuanhuaanddianji', 'pinpai_click', 'pinpai_buy_lv'],
      dtype='object')

In [36]:
# X_pre = data2[['item_category_list','item_property_list',
#           'zhuanhualv','relaofzhuanhuaanddianji', 
#           'pinpai_buy_lv', 'pinpai_click',
#           'shop_review_positive_rate','shop_score_service',
#          'shop_score_delivery','shop_score_description','shop_star_level'
#           ,'shop_review_num_level','item_price_level','item_sales_level',
#          'item_collected_level','item_pv_level',
#           'user_gender_id','user_age_level',
#           'user_occupation_id','user_star_level',
#           'context_page_id','context_timestamp']]
X_pre = data2[[ 
          'shop_review_positive_rate','shop_score_service',
         'shop_score_delivery','shop_score_description','shop_star_level'
          ,'shop_review_num_level','item_price_level','item_sales_level',
         'item_collected_level','item_pv_level',
          'user_gender_id','user_age_level',
          'user_occupation_id','user_star_level','item_category_list_num','item_property_list_num',
          'context_page_id','context_timestamp',
            'like_top_one_jiageclick','like_top_two_jiageclick','like_top_three_jiageclick'
            ,'clickpv']]
X_pre = np.array(X_pre,dtype='float')

In [37]:
X_pre[10,:]

array([  1.00000000e+00,   9.79252459e-01,   9.80537705e-01,
         9.85626230e-01,   5.01200000e+03,   1.50000000e+01,
         8.00000000e+00,   1.00000000e+01,   1.30000000e+01,
         1.50000000e+01,   1.00000000e+00,   1.00200000e+03,
         2.00500000e+03,   3.00700000e+03,   2.00000000e+00,
         3.00000000e+00,   4.00100000e+03,   6.66277000e+05,
         2.24410000e+04,   1.47650000e+04,   7.63000000e+02,
         1.00000000e-02])

## 分箱

In [38]:
#item_price_level
# bins = np.linspace(-0.5, 2.5, 4)
sha = train.shape[1]
for i in range(4,sha-5):
# i = 4
# if True:
    print((X_train[:,i][X_train[:,i]>=0].max()+1.5)-(X_train[:,i][X_train[:,i]>=0].min()-0.5))
    bins = np.arange(X_train[:,i][(X_train[:,i]>=0)].min()-0.5, X_train[:,i][X_train[:,i]>=0].max()+1.5, 1)
    bins = np.hstack(([-1.5],bins))
    which_bin = np.digitize(train[:,i].reshape(-1, 1), bins=bins)
    encoder = OneHotEncoder(sparse=False)
    encoder.fit(which_bin)
    X_train_binned = encoder.transform(which_bin)



    which_bin = np.digitize(test[:,i].reshape(-1, 1), bins=bins)
#     encoder = OneHotEncoder(sparse=False)
#     encoder.fit(which_bin)
    X_test_binned = encoder.transform(which_bin)
    
    which_bin = np.digitize(X_pre[:,i].reshape(-1, 1), bins=bins)
#     encoder = OneHotEncoder(sparse=False)
#     encoder.fit(which_bin)
    X_pre_binned = encoder.transform(which_bin)
    print(bins)
    if (np.hstack((train,X_train_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
        if (np.hstack((X_pre,X_pre_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
            train = np.hstack((train,X_train_binned))
            test = np.hstack((test,X_test_binned))
            X_pre = np.hstack((X_pre,X_pre_binned))
            print("0k")
    else:
        print("No")

23.0
[ -1.50000000e+00   4.99850000e+03   4.99950000e+03   5.00050000e+03
   5.00150000e+03   5.00250000e+03   5.00350000e+03   5.00450000e+03
   5.00550000e+03   5.00650000e+03   5.00750000e+03   5.00850000e+03
   5.00950000e+03   5.01050000e+03   5.01150000e+03   5.01250000e+03
   5.01350000e+03   5.01450000e+03   5.01550000e+03   5.01650000e+03
   5.01750000e+03   5.01850000e+03   5.01950000e+03   5.02050000e+03]
0k
27.0
[ -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5
  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5  18.5  19.5  20.5  21.5
  22.5  23.5  24.5  25.5]
0k
19.0
[ -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5
  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5]
0k
18.0
[ -1.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5  10.5
  11.5  12.5  13.5  14.5  15.5  16.5  17.5]
0k
19.0
[ -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5
  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5]
0k
23.0
[ -1.

In [39]:
bins = np.linspace(0, 86400,49)
print(bins)
bins = np.hstack(([-1.5],bins))
which_bin = np.digitize(train[:,17].reshape(-1, 1), bins=bins)
encoder = OneHotEncoder(sparse=False)
encoder.fit(which_bin)
X_train_binned = encoder.transform(which_bin)



which_bin = np.digitize(test[:,17].reshape(-1, 1), bins=bins)
# encoder = OneHotEncoder(sparse=False)
# encoder.fit(which_bin)
X_test_binned = encoder.transform(which_bin)

which_bin = np.digitize(X_pre[:,17].reshape(-1, 1), bins=bins)
# encoder = OneHotEncoder(sparse=False)
# encoder.fit(which_bin)
X_pre_binned = encoder.transform(which_bin)
print(bins)
if (np.hstack((train,X_train_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
    if (np.hstack((X_pre,X_pre_binned)).shape[1] == np.hstack((test,X_test_binned)).shape[1]):
        train = np.hstack((train,X_train_binned))
        test = np.hstack((test,X_test_binned))
        X_pre = np.hstack((X_pre,X_pre_binned))
        print("0k")
else:
    print("No")

[     0.   1800.   3600.   5400.   7200.   9000.  10800.  12600.  14400.
  16200.  18000.  19800.  21600.  23400.  25200.  27000.  28800.  30600.
  32400.  34200.  36000.  37800.  39600.  41400.  43200.  45000.  46800.
  48600.  50400.  52200.  54000.  55800.  57600.  59400.  61200.  63000.
  64800.  66600.  68400.  70200.  72000.  73800.  75600.  77400.  79200.
  81000.  82800.  84600.  86400.]
[ -1.50000000e+00   0.00000000e+00   1.80000000e+03   3.60000000e+03
   5.40000000e+03   7.20000000e+03   9.00000000e+03   1.08000000e+04
   1.26000000e+04   1.44000000e+04   1.62000000e+04   1.80000000e+04
   1.98000000e+04   2.16000000e+04   2.34000000e+04   2.52000000e+04
   2.70000000e+04   2.88000000e+04   3.06000000e+04   3.24000000e+04
   3.42000000e+04   3.60000000e+04   3.78000000e+04   3.96000000e+04
   4.14000000e+04   4.32000000e+04   4.50000000e+04   4.68000000e+04
   4.86000000e+04   5.04000000e+04   5.22000000e+04   5.40000000e+04
   5.58000000e+04   5.76000000e+04   5.94000000e+

In [40]:
test.shape

(119535, 253)

In [41]:
# PF = PolynomialFeatures(degree=2)
# PF.fit(train)
# X_train = PF.transform(train)
# X_test = PF.transform(test)

In [42]:
SS = StandardScaler()
SS.fit(train)
train = SS.transform(train)
test = SS.transform(test)
X_pre = SS.transform(X_pre)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.externals import joblib
from sklearn.metrics import log_loss
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC

import xgboost as xgb
import lightgbm as lgb

In [44]:
model_xgb.fit?

Object `model_xgb.fit` not found.


In [45]:
model_xgb = xgb.XGBClassifier( n_estimators=500,random_state =666, nthread = -1,n_jobs=-1)

In [46]:
model_xgb.fit(train, Y_train,eval_metric='logloss')

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=500,
       n_jobs=-1, nthread=-1, objective='binary:logistic',
       random_state=666, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1)

In [47]:
xgb_train_pred = model_xgb.predict_proba(train)
log_loss(Y_train, xgb_train_pred[:,1])

0.086153028702003032

In [48]:
xgb_test_pred = model_xgb.predict_proba(test)
log_loss(Y_test, xgb_test_pred[:,1])

0.08812491542834136

In [49]:
model_xgb.predict_proba(X_pre)[:,1]

array([ 0.00514216,  0.0117336 ,  0.01081135, ...,  0.00970177,
        0.01062392,  0.00704453], dtype=float32)

In [50]:
# del(model_xgb)

In [51]:
xgb1 = model_xgb

In [52]:
lgb.LGBMClassifier?

In [53]:
model_lgb = lgb.LGBMClassifier(n_estimators=200,n_jobs=-1,min_child_samples=700,
                              feature_fraction_seed=666, bagging_seed=666
                              )
# model_lgb = lgb.LGBMClassifier(objective='binary',
#                         num_leaves=164,
#                         n_estimators=500,
#                         colsample_bytree = 0.65,
#                         subsample = 0.75, max_depth=7,
#                               )

In [54]:
model_lgb.fit(train, Y_train,eval_metric='binary_logloss')

LGBMClassifier(bagging_seed=666, boosting_type='gbdt', class_weight=None,
        colsample_bytree=1.0, feature_fraction_seed=666, learning_rate=0.1,
        max_depth=-1, min_child_samples=700, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=200, n_jobs=-1, num_leaves=31,
        objective=None, random_state=None, reg_alpha=0.0, reg_lambda=0.0,
        silent=True, subsample=1.0, subsample_for_bin=200000,
        subsample_freq=1)

In [55]:
# lgb_train_pred = model_lgb.predict_proba(train)
lgb_train_pred = model_lgb.predict_proba(train)
log_loss(Y_train, lgb_train_pred[:,1])

0.082285134459819276

In [56]:
# lgb_test_pred = model_lgb.predict_proba(test)
lgb_test_pred = model_lgb.predict_proba(test)
log_loss(Y_test, lgb_test_pred[:,1])

0.088312674934251906

In [57]:
model_lgb.predict_proba(X_pre)[:,1]

array([ 0.00436128,  0.03563317,  0.02146312, ...,  0.0208593 ,
        0.0174051 ,  0.0100824 ])

In [47]:
876

876

In [69]:
lgb_test_pred = model_lgb.predict_proba(train)
xgb_test_pred = model_xgb.predict_proba(train)
log_loss(Y_train, (xgb_test_pred[:,1]+xgb_test_pred[:,1])/2)

0.086217756393743128

In [70]:
lgb_test_pred = model_lgb.predict_proba(test)
xgb_test_pred = model_xgb.predict_proba(test)
log_loss(Y_test, (xgb_test_pred[:,1]+xgb_test_pred[:,1])/2)

0.088140701326921103

In [71]:
log_reg = LogisticRegression(C = 0.001,penalty='l1')
log_reg.fit(train, Y_train)

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [72]:
log_loss(Y_train, log_reg.predict_proba(train)[:,1])

0.092675027979856897

In [73]:
log_loss(Y_test, log_reg.predict_proba(test)[:,1])

0.090791575030362837

In [74]:
log_reg.predict_proba(test)[:,1]

array([ 0.01554595,  0.02741046,  0.01857791, ...,  0.02519158,
        0.02110347,  0.02519158])

In [75]:
lgb_test_pred = model_lgb.predict_proba(train)
xgb_test_pred = model_xgb.predict_proba(train)
X_add = np.hstack((lgb_test_pred, xgb_test_pred))

In [76]:
log_all = LogisticRegression()
log_all.fit(X_add, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [77]:
log_loss(Y_train, log_all.predict_proba(X_add)[:,1])

0.084304288167431241

In [78]:
lgb_test_pred = model_lgb.predict_proba(test)
xgb_test_pred = model_xgb.predict_proba(test)
X_add = np.hstack((lgb_test_pred, xgb_test_pred))

In [79]:
log_loss(Y_test, log_all.predict_proba(X_add)[:,1])

0.090191640740099985

In [86]:
lgb_test_pred = model_lgb.predict_proba(test)
xgb_test_pred = model_xgb.predict_proba(test)
X_add = np.hstack((lgb_test_pred, xgb_test_pred))

In [87]:
log_loss(Y_test, log_all.predict_proba(X_add)[:,1])

0.089341417337129275

In [88]:
# BC = BaggingClassifier(base_estimator=LogisticRegression(C = 0.01), random_state=666, n_estimators=30)
# BC.fit(train, Y_train)

In [89]:
# log_loss(Y_train, BC.predict_proba(train))

In [29]:
# log_loss(Y_test, BC.predict_proba(test))

In [30]:
# log_reg.predict_proba(train)[:,1]

In [31]:
# ETR = joblib.load('allETR.pkl')
# ETR = ExtraTreesClassifier(n_estimators=300, n_jobs=-1, random_state=666, max_depth=500)#0.41
# ETR.fit(train, Y_train)

In [32]:
# log_loss(Y_train, ETR.predict_proba(train)[:,1])

In [33]:
# log_loss(Y_test, ETR.predict_proba(test)[:,1])

In [34]:
# joblib.dump(ETR, 'allETR.pkl') 

In [114]:
# MNB = MultinomialNB(alpha=1)
# MNB.fit(train+1, Y_train)

In [ ]:
log_loss(Y_test, MNB.predict_proba(test+1)[:,1])

In [37]:
BNB = BernoulliNB(alpha=1)
BNB.fit(train+1, Y_train)

BernoulliNB(alpha=1, binarize=0.0, class_prior=None, fit_prior=True)

In [38]:
log_loss(Y_test, BNB.predict_proba(test)[:,1])

33.901286592858881

In [63]:
log_loss(Y_test, np.ones([Y_test.shape[0],1])*0.01*4)

0.099552248514805805

In [51]:
np.ones([Y_test.shape[0],1])*0.000000001*4

array([[  4.00000000e-09],
       [  4.00000000e-09],
       [  4.00000000e-09],
       ..., 
       [  4.00000000e-09],
       [  4.00000000e-09],
       [  4.00000000e-09]])

In [48]:
np.zeros([Y_test.shape[0],1])

array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [39]:
# last = LogisticRegression(C = 0.0008,penalty='l2')

# # log_reg.fit(train, Y_train)
# # ETR.fit(train, Y_train)
# # MNB.fit(train+1, Y_train)
# # BNB.fit(train+1, Y_train)
# c_data = log_reg.predict_proba(train)[:, 1].reshape(-1, 1)
# c_data = np.hstack((c_data,ETR.predict_proba(train)[:, 1].reshape(-1, 1)))
# c_data = np.hstack((c_data,MNB.predict_proba(train+1)[:, 1].reshape(-1, 1)))
# # c_data = np.hstack((c_data,BNB.predict_proba(train+1)[:, 1].reshape(-1, 1)))
# last.fit(c_data,Y_train)


In [40]:
# Y_pre1 = log_reg.predict_proba(train)[:, 1].reshape(-1, 1)
# Y_pre2 = ETR.predict_proba(train)[:, 1].reshape(-1, 1)
# Y_pre3 = MNB.predict_proba(train+1)[:, 1].reshape(-1, 1)
# # Y_pre4 = BNB.predict_proba(train+1)[:, 1].reshape(-1, 1)
# Y_add = np.hstack((Y_pre1, Y_pre2))
# Y_add = np.hstack((Y_add, Y_pre3))
# # Y_add = np.hstack((Y_add, Y_pre4))
# Y_pre = last.predict_proba(Y_add)

In [41]:
# log_loss(Y_train, Y_pre)

In [42]:
# log_loss(Y_test, last.predict_proba(np.hstack((log_reg.predict_proba(test)[:, 1].reshape(-1, 1),ETR.predict_proba(test)[:, 1].reshape(-1, 1)))))

In [43]:
# Y_pre1 = log_reg.predict_proba(test)[:, 1].reshape(-1, 1)
# Y_pre2 = ETR.predict_proba(test)[:, 1].reshape(-1, 1)
# Y_pre3 = MNB.predict_proba(test+1)[:, 1].reshape(-1, 1)
# # Y_pre4 = BNB.predict_proba(test+1)[:, 1].reshape(-1, 1)
# Y_add = np.hstack((Y_pre1, Y_pre2))
# Y_add = np.hstack((Y_add, Y_pre3))
# # Y_add = np.hstack((Y_add, Y_pre4))
# Y_pre = last.predict_proba(Y_add)

# # Y_pre = Y_pre1 + Y_pre2 + Y_pre3 + Y_pre4
# # Y_pre = Y_pre/4

In [44]:
# log_loss(Y_test, Y_pre)

In [45]:
# Y_pre = ETR.predict_proba(X_pre)
# Y_pre

In [80]:
Y_pre = model_xgb.predict_proba(X_pre)[:,1]
Y_pre = Y_pre.reshape(-1,1)
Y_prelist = Y_pre.tolist()

In [81]:
Y_prelist

[[0.004298010375350714],
 [0.014693550765514374],
 [0.014427660033106804],
 [0.011915729381144047],
 [0.010095817968249321],
 [0.009725315496325493],
 [0.01792435348033905],
 [0.004604210611432791],
 [0.003110608085989952],
 [0.0037869270890951157],
 [0.002748334314674139],
 [0.0033882129937410355],
 [0.0029524320270866156],
 [0.023514630272984505],
 [0.0033608591184020042],
 [0.002968747867271304],
 [0.010733350180089474],
 [0.006597795989364386],
 [0.004450063221156597],
 [0.0047917915508151054],
 [0.013064715079963207],
 [0.00225290609523654],
 [0.0011366641847416759],
 [0.0018032334046438336],
 [0.002483227290213108],
 [0.0010610754834488034],
 [0.0018027801997959614],
 [0.0017053945921361446],
 [0.003395600477233529],
 [0.002525920746847987],
 [0.0016954044112935662],
 [0.0026182138826698065],
 [0.0011366641847416759],
 [0.002295545069500804],
 [0.002009764313697815],
 [0.0010576883796602488],
 [0.002479753689840436],
 [0.0029982104897499084],
 [0.0021977496799081564],
 [0.0026433

In [65]:
Y_pre = (model_lgb.predict_proba(X_pre)[:,1]+model_xgb.predict_proba(X_pre)[:,1])/2
Y_pre = Y_pre.reshape(-1,1)
Y_prelist = Y_pre.tolist()

In [92]:
# sub = pd.DataFrame()
# sub['instance_id'] = np.array(data2[['instance_id']],dtype='float').ravel()
# sub['predicted_score'] = Y_pre[:,1].ravel()
# sub.to_csv('submission.csv',index=False)

In [82]:
instance_id = np.array(data2[['instance_id']],dtype='float').ravel()
instance_idlist = instance_id.tolist()
with open('111.txt', 'w') as f:
    f.write("instance_id predicted_score\r") 
    for i in range(Y_pre.shape[0]):
        f.write(str(data2[['instance_id']].iloc[i,0]) + " " + str(Y_pre[i][0]) + '\r') 
#         f.write(str(data2[['instance_id']].iloc[i,0]) + " " + str('%.15f'%Y_pre[i,0]) + '\r') 

In [436]:
Y_pre.shape[0]

18371

In [570]:
np.set_printoptions(suppress=True)

In [584]:
'%.15f'%Y_pre[0,0]

'0.000002709476912'

In [50]:
# data2[['instance_id']]

In [51]:
# sub = pd.DataFrame()
# sub['instance_id'] = data2.pop('instance_id')
# sub['predicted_score'] = Y_pre[:,1].ravel().reshape(-1, 1)
# sub.to_csv('000.txt',index=False, sep=' ')